### ISSUE TITLE
wallet is not syncing

### ISSUE THREAD

**Issue by Pacius** [HyperspaceApp/Hyperspace.app#1]
How to set a proxy?and can you give some nodes or dns seed

**Comment by huetsch** [comment]
Are you still having issues? We don't have that many bootstrap nodes yet, but I haven't heard too many syncing complaints so far.

**Comment by Pacius** [comment]
It's fine now.but there is anothre problem,how could we mine the space properly?I tried build-in miner,and blocks are getting higher,but not a single space were generated in my wallet.

**Comment by huetsch** [comment]
Mining SPACE currently requires a dedicated ASIC hardware miner, such as an A3 or S11.

**Comment by KookaburraCoder** [comment]
I have a Macbook Pro and I have the Hyperspace app installed; I have a wallet but it doesn't sync.

I even tried installing it on a windows computer here and get the same problem.

"Not Synchronizing"

Does this app require ports open or anything else?

I'd check the website but I cannot access it, seems to be down.

![image](https://user-images.githubusercontent.com/40506406/103123543-70877700-46d0-11eb-94ba-f86154f9faa0.png)
